//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 09:24:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://se.havero/phonenumber")
package https.se_havero.phonenumber;
